/// Statische Liste der Weltwährungen (ISO 4217) mit Symbol, englischem Namen und
/// Anzahl Nachkommastellen. Quelle für Auswahl (Suche), Symbol-Anzeige und
/// korrekte Formatierung. Bewusst als const im Code (kein Netz/keine Datei nötig).
///
/// Nicht gelistete/eigene Codes (z. B. Krypto) bleiben möglich – dann gilt der
/// Code selbst als „Symbol" und 2 Nachkommastellen.
class WorldCurrency {
  const WorldCurrency(this.code, this.name, this.symbol, [this.decimals = 2]);

  final String code;
  final String name;
  final String symbol;
  final int decimals;
}

const worldCurrencies = <WorldCurrency>[
  WorldCurrency('AED', 'UAE Dirham', 'د.إ'),
  WorldCurrency('AFN', 'Afghan Afghani', '؋'),
  WorldCurrency('ALL', 'Albanian Lek', 'L'),
  WorldCurrency('AMD', 'Armenian Dram', '֏'),
  WorldCurrency('ANG', 'Netherlands Antillean Guilder', 'ƒ'),
  WorldCurrency('AOA', 'Angolan Kwanza', 'Kz'),
  WorldCurrency('ARS', 'Argentine Peso', r'$'),
  WorldCurrency('AUD', 'Australian Dollar', r'A$'),
  WorldCurrency('AWG', 'Aruban Florin', 'ƒ'),
  WorldCurrency('AZN', 'Azerbaijani Manat', '₼'),
  WorldCurrency('BAM', 'Bosnia-Herzegovina Convertible Mark', 'KM'),
  WorldCurrency('BBD', 'Barbadian Dollar', r'$'),
  WorldCurrency('BDT', 'Bangladeshi Taka', '৳'),
  WorldCurrency('BGN', 'Bulgarian Lev', 'лв'),
  WorldCurrency('BHD', 'Bahraini Dinar', '.د.ب', 3),
  WorldCurrency('BIF', 'Burundian Franc', 'FBu', 0),
  WorldCurrency('BMD', 'Bermudan Dollar', r'$'),
  WorldCurrency('BND', 'Brunei Dollar', r'$'),
  WorldCurrency('BOB', 'Bolivian Boliviano', 'Bs'),
  WorldCurrency('BRL', 'Brazilian Real', r'R$'),
  WorldCurrency('BSD', 'Bahamian Dollar', r'$'),
  WorldCurrency('BTN', 'Bhutanese Ngultrum', 'Nu.'),
  WorldCurrency('BWP', 'Botswanan Pula', 'P'),
  WorldCurrency('BYN', 'Belarusian Ruble', 'Br'),
  WorldCurrency('BZD', 'Belize Dollar', r'BZ$'),
  WorldCurrency('CAD', 'Canadian Dollar', r'CA$'),
  WorldCurrency('CDF', 'Congolese Franc', 'FC'),
  WorldCurrency('CHF', 'Swiss Franc', 'CHF'),
  WorldCurrency('CLP', 'Chilean Peso', r'$', 0),
  WorldCurrency('CNY', 'Chinese Yuan', '¥'),
  WorldCurrency('COP', 'Colombian Peso', r'$'),
  WorldCurrency('CRC', 'Costa Rican Colón', '₡'),
  WorldCurrency('CUP', 'Cuban Peso', r'$'),
  WorldCurrency('CVE', 'Cape Verdean Escudo', r'$'),
  WorldCurrency('CZK', 'Czech Koruna', 'Kč'),
  WorldCurrency('DJF', 'Djiboutian Franc', 'Fdj', 0),
  WorldCurrency('DKK', 'Danish Krone', 'kr'),
  WorldCurrency('DOP', 'Dominican Peso', r'RD$'),
  WorldCurrency('DZD', 'Algerian Dinar', 'دج'),
  WorldCurrency('EGP', 'Egyptian Pound', '£'),
  WorldCurrency('ERN', 'Eritrean Nakfa', 'Nfk'),
  WorldCurrency('ETB', 'Ethiopian Birr', 'Br'),
  WorldCurrency('EUR', 'Euro', '€'),
  WorldCurrency('FJD', 'Fijian Dollar', r'$'),
  WorldCurrency('FKP', 'Falkland Islands Pound', '£'),
  WorldCurrency('GBP', 'British Pound', '£'),
  WorldCurrency('GEL', 'Georgian Lari', '₾'),
  WorldCurrency('GHS', 'Ghanaian Cedi', '₵'),
  WorldCurrency('GIP', 'Gibraltar Pound', '£'),
  WorldCurrency('GMD', 'Gambian Dalasi', 'D'),
  WorldCurrency('GNF', 'Guinean Franc', 'FG', 0),
  WorldCurrency('GTQ', 'Guatemalan Quetzal', 'Q'),
  WorldCurrency('GYD', 'Guyanaese Dollar', r'$'),
  WorldCurrency('HKD', 'Hong Kong Dollar', r'HK$'),
  WorldCurrency('HNL', 'Honduran Lempira', 'L'),
  WorldCurrency('HRK', 'Croatian Kuna', 'kn'),
  WorldCurrency('HTG', 'Haitian Gourde', 'G'),
  WorldCurrency('HUF', 'Hungarian Forint', 'Ft'),
  WorldCurrency('IDR', 'Indonesian Rupiah', 'Rp'),
  WorldCurrency('ILS', 'Israeli New Shekel', '₪'),
  WorldCurrency('INR', 'Indian Rupee', '₹'),
  WorldCurrency('IQD', 'Iraqi Dinar', 'ع.د', 3),
  WorldCurrency('IRR', 'Iranian Rial', '﷼'),
  WorldCurrency('ISK', 'Icelandic Króna', 'kr', 0),
  WorldCurrency('JMD', 'Jamaican Dollar', r'J$'),
  WorldCurrency('JOD', 'Jordanian Dinar', 'د.ا', 3),
  WorldCurrency('JPY', 'Japanese Yen', '¥', 0),
  WorldCurrency('KES', 'Kenyan Shilling', 'KSh'),
  WorldCurrency('KGS', 'Kyrgystani Som', 'с'),
  WorldCurrency('KHR', 'Cambodian Riel', '៛'),
  WorldCurrency('KMF', 'Comorian Franc', 'CF', 0),
  WorldCurrency('KRW', 'South Korean Won', '₩', 0),
  WorldCurrency('KWD', 'Kuwaiti Dinar', 'د.ك', 3),
  WorldCurrency('KYD', 'Cayman Islands Dollar', r'$'),
  WorldCurrency('KZT', 'Kazakhstani Tenge', '₸'),
  WorldCurrency('LAK', 'Laotian Kip', '₭'),
  WorldCurrency('LBP', 'Lebanese Pound', 'ل.ل'),
  WorldCurrency('LKR', 'Sri Lankan Rupee', 'Rs'),
  WorldCurrency('LRD', 'Liberian Dollar', r'$'),
  WorldCurrency('LSL', 'Lesotho Loti', 'L'),
  WorldCurrency('LYD', 'Libyan Dinar', 'ل.د', 3),
  WorldCurrency('MAD', 'Moroccan Dirham', 'د.م.'),
  WorldCurrency('MDL', 'Moldovan Leu', 'L'),
  WorldCurrency('MGA', 'Malagasy Ariary', 'Ar'),
  WorldCurrency('MKD', 'Macedonian Denar', 'ден'),
  WorldCurrency('MMK', 'Myanmar Kyat', 'K'),
  WorldCurrency('MNT', 'Mongolian Tugrik', '₮'),
  WorldCurrency('MOP', 'Macanese Pataca', 'MOP\$'),
  WorldCurrency('MRU', 'Mauritanian Ouguiya', 'UM'),
  WorldCurrency('MUR', 'Mauritian Rupee', '₨'),
  WorldCurrency('MVR', 'Maldivian Rufiyaa', 'Rf'),
  WorldCurrency('MWK', 'Malawian Kwacha', 'MK'),
  WorldCurrency('MXN', 'Mexican Peso', r'$'),
  WorldCurrency('MYR', 'Malaysian Ringgit', 'RM'),
  WorldCurrency('MZN', 'Mozambican Metical', 'MT'),
  WorldCurrency('NAD', 'Namibian Dollar', r'$'),
  WorldCurrency('NGN', 'Nigerian Naira', '₦'),
  WorldCurrency('NIO', 'Nicaraguan Córdoba', r'C$'),
  WorldCurrency('NOK', 'Norwegian Krone', 'kr'),
  WorldCurrency('NPR', 'Nepalese Rupee', '₨'),
  WorldCurrency('NZD', 'New Zealand Dollar', r'NZ$'),
  WorldCurrency('OMR', 'Omani Rial', 'ر.ع.', 3),
  WorldCurrency('PAB', 'Panamanian Balboa', 'B/.'),
  WorldCurrency('PEN', 'Peruvian Sol', 'S/'),
  WorldCurrency('PGK', 'Papua New Guinean Kina', 'K'),
  WorldCurrency('PHP', 'Philippine Peso', '₱'),
  WorldCurrency('PKR', 'Pakistani Rupee', '₨'),
  WorldCurrency('PLN', 'Polish Zloty', 'zł'),
  WorldCurrency('PYG', 'Paraguayan Guarani', '₲', 0),
  WorldCurrency('QAR', 'Qatari Rial', 'ر.ق'),
  WorldCurrency('RON', 'Romanian Leu', 'lei'),
  WorldCurrency('RSD', 'Serbian Dinar', 'дин.'),
  WorldCurrency('RUB', 'Russian Ruble', '₽'),
  WorldCurrency('RWF', 'Rwandan Franc', 'FRw', 0),
  WorldCurrency('SAR', 'Saudi Riyal', 'ر.س'),
  WorldCurrency('SBD', 'Solomon Islands Dollar', r'$'),
  WorldCurrency('SCR', 'Seychellois Rupee', '₨'),
  WorldCurrency('SDG', 'Sudanese Pound', 'ج.س.'),
  WorldCurrency('SEK', 'Swedish Krona', 'kr'),
  WorldCurrency('SGD', 'Singapore Dollar', r'S$'),
  WorldCurrency('SHP', 'Saint Helena Pound', '£'),
  WorldCurrency('SLE', 'Sierra Leonean Leone', 'Le'),
  WorldCurrency('SOS', 'Somali Shilling', 'Sh'),
  WorldCurrency('SRD', 'Surinamese Dollar', r'$'),
  WorldCurrency('SSP', 'South Sudanese Pound', '£'),
  WorldCurrency('STN', 'São Tomé and Príncipe Dobra', 'Db'),
  WorldCurrency('SYP', 'Syrian Pound', '£'),
  WorldCurrency('SZL', 'Swazi Lilangeni', 'L'),
  WorldCurrency('THB', 'Thai Baht', '฿'),
  WorldCurrency('TJS', 'Tajikistani Somoni', 'ЅМ'),
  WorldCurrency('TMT', 'Turkmenistani Manat', 'm'),
  WorldCurrency('TND', 'Tunisian Dinar', 'د.ت', 3),
  WorldCurrency('TOP', 'Tongan Paʻanga', r'T$'),
  WorldCurrency('TRY', 'Turkish Lira', '₺'),
  WorldCurrency('TTD', 'Trinidad & Tobago Dollar', r'TT$'),
  WorldCurrency('TWD', 'New Taiwan Dollar', r'NT$'),
  WorldCurrency('TZS', 'Tanzanian Shilling', 'TSh'),
  WorldCurrency('UAH', 'Ukrainian Hryvnia', '₴'),
  WorldCurrency('UGX', 'Ugandan Shilling', 'USh', 0),
  WorldCurrency('USD', 'US Dollar', r'$'),
  WorldCurrency('UYU', 'Uruguayan Peso', r'$U'),
  WorldCurrency('UZS', 'Uzbekistani Som', 'soʻm'),
  WorldCurrency('VES', 'Venezuelan Bolívar', 'Bs.'),
  WorldCurrency('VND', 'Vietnamese Dong', '₫', 0),
  WorldCurrency('VUV', 'Vanuatu Vatu', 'VT', 0),
  WorldCurrency('WST', 'Samoan Tala', r'WS$'),
  WorldCurrency('XAF', 'Central African CFA Franc', 'FCFA', 0),
  WorldCurrency('XCD', 'East Caribbean Dollar', r'$'),
  WorldCurrency('XOF', 'West African CFA Franc', 'CFA', 0),
  WorldCurrency('XPF', 'CFP Franc', '₣', 0),
  WorldCurrency('YER', 'Yemeni Rial', '﷼'),
  WorldCurrency('ZAR', 'South African Rand', 'R'),
  WorldCurrency('ZMW', 'Zambian Kwacha', 'ZK'),
  WorldCurrency('ZWL', 'Zimbabwean Dollar', r'$'),
];

/// Schneller Zugriff Code -> Währung.
final worldCurrencyByCode = <String, WorldCurrency>{
  for (final c in worldCurrencies) c.code: c,
};

/// Alle bekannten ISO-Codes (sortiert).
final worldCurrencyCodes = worldCurrencies.map((c) => c.code).toList();
